name: CI

on:
  # push: # start when push in main branch
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      package-manager:
        description: 'Package manager to use (npm, yarn, etc.)'
        required: true
        default: 'npm' # default value
      command:
        description: 'Build command'
        required: true
        default: 'npm run build' # default value
      build-folder:
        description: 'Build folder path'
        required: true
        default: './dist' # default value

jobs:
  curl-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send data using curl
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "packageManager": "${{ github.event.inputs.package-manager }}",
              "command": "${{ github.event.inputs.command }}",
              "buildFolder": "${{ github.event.inputs.build-folder }}"
            }' \
            https://test-echo-server-production.up.railway.app/echo
