name: Test custom action

on:
  workflow_dispatch:

jobs:
  curl-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check test action 
        uses: AnatoliiYarovyi/test-custom-action@v0.0.4
        with:
          who-to-greet: "Mona the Octocat"
